### ISSUE TITLE
The tittle of downloaded videos is wrong

### ISSUE THREAD

**Issue by not-programmer98** [N0-0NE-Dev/NoFasel#36]
**Describe the bug**
When I download a movie it names the file with numbers and quality not the movie or episode name

**To Reproduce**
1.Go to any series any episode 
2.copy the url 
3.put it in the download manager
4.the name isn't convenient
 
**Expected behavior**
I expect to see the movie or series name and number of episode

**Screenshots**
![Imagepipe_0](https://user-images.githubusercontent.com/126913926/222819499-6e7eddfd-b2fd-4fec-8496-cc8393a4680b.jpg)

**Smartphone (please complete the following information):**
It's not related to a specific phone

**Additional context**
It would be more convenient if you replaced the button copy with share button to be more easy to pass to a download manager

**Comment by N0-0NE-Dev** [comment]
Nothing I can do about this, I don't own or operate the servers which contain the m3u8 files.

**Comment by not-programmer98** [comment]
Couldn't you add a way to download it with it's title?
When I get the download link from the site and but it in a download manager it gives me the right name, what's the difference here

**Comment by N0-0NE-Dev** [comment]
Your download manager automatically detects the name of the file, what you are trying to download currently is not an mp4 file, it's an m3u8 file basically it has the movie (or episode) you are trying to download in multiple segments, your download manager downloads all these segments and then combine them all into one mp4 file. Downloading such files in the app will be slow, clunky and complex that's why I removed the download button from fasel content. I am working on scraping cimanow which will provide an overall better downloading experience.

**Comment by N0-0NE-Dev** [comment]
> I think wecima a good option for downloads.

Wecima lists episodes individually which makes it hard to scrape and organise.
